### ISSUE TITLE
GreensFun

### ISSUE THREAD

**Issue by MikaelSlevinsky** [ApproxFun/SIE.jl#11]
Should be a sum-of-products of `ProductFun`s with Log and Cauchy weights.

For kernels of convolution-type, i.e. K(x,y) = K(y-x), there should be a cross-over point between using the O(n) function evaluation + O(n^3) arithmetic Chebyshev addition formula and the original `ProductFun` constructor with O(n^2) function evaluation + O(n^2 log n) arithmetic via fast transforms.

The cross-over point is TBD, but a 1D antidiagonal expansion may help in determining the size of the `ProductFun` via the original construction instead of calling an adaptive routine.

The O(n) function evaluation + O(n log n) arithmetic periodic cases are clear winners.

**Comment by MikaelSlevinsky** [comment]
Using a Bessel function as the kernel (which will be typical as they are a considerable family of fundamental solutions for 2D PDEs) the breakpoint between the coefficient addition and fast transforms is, rounded to the nearest hundred, 3000. I can elaborate more if it's necessary.

**Comment by MikaelSlevinsky** [comment]
Do you think `ProductFun` could take a keyword `method` and have `:normal` or `:symmetric` as values?

**Comment by MikaelSlevinsky** [comment]
I would like to see `ProductFun`s take a `TensorSpace` of `PiecewiseSpace`s. The result would be an Array of `GreensFun`s. Then, we could define `PrincipalValue` of an Array of `GreensFun`s element wise, and we'd be done.

**Comment by dlfivefifty** [comment]
Sure!

**Comment by MikaelSlevinsky** [comment]
I think we can take advantage of an analogy to FMM to reduce the size of off-diagonal kernels. If the domains are far apart, the connection coefficients can be some orders of magnitude smaller than the (pick your) norm of the block diagonal coefficients. Ideally, off-diagonal kernels should be generated with an absolute accuracy determined by the diagonal blocks.

**Comment by dlfivefifty** [comment]
You mean for evaluating the solution?

	Could also be useful for the solve by using Woodbury formula or Schur complement formula to iteratively block-diagonalize the equation.

**Comment by MikaelSlevinsky** [comment]
I was originally thinking about the solve step, but it might help for evaluating the solution as well.

**Comment by MikaelSlevinsky** [comment]
`GreensFun` is a type of `BivariateFun` that holds a vector of bivariate kernels with different orders of diagonal singularities. Arrays of `GreensFun`s can be built and allow for the simple and user-friendly notation:
```julia
∂u∂n = ⨍[G]\uiΓ
```
to solve for single-layer densities given incident fields on the contour Γ.
