### ISSUE TITLE
Use ⨍ and ⨎?  :)

### ISSUE THREAD

**Issue by dlfivefifty** [ApproxFun/SIE.jl#14]
Was going through the unicode math symbols and realized they include ⨍ and ⨎.  Surely We can use these somehow for writing hilbert??  This would be cool if it worked:

x=Fun(identity)

⨍(exp(x)*sqrt(1-x^2)/(x-0.1))

**Comment by dlfivefifty** [comment]
PS how do you feel about

∫(f::Fun)=integrate(f)
Σ(f::Fun)=sum(f)

I guess also ∫(S::FunctionSpace)=Integral(S).  Not entirely sure about Σ as definite integral...

**Comment by MikaelSlevinsky** [comment]
Those are cheeky! in favour

if i wanted to access them from command completion, do you know what they are?

I used Sigma because in Chebfun the analogy is always drawn between discrete and continuous, but with all these symbols at our disposal...

**Comment by dlfivefifty** [comment]
I think we have mostly moved away from that analogy, since we do f*g instead of f.*g.   The only left overs are diff (I’m in the process of adding ‘ so that might be removed..have to think of a good shorthand for partial differentiation first though), cumsum, sum and Σ I believe.  I can’t think of a good alternative name for cumsum and sum.  Right now I’m thinking of leaving Σ as definite integral, using  ∫ as indefinite integral and ⨜ can be cumsum.  

But it’s probably good to have written out names for things. We violate this for Σ since not everyone has a Mac to do option-w.  And also ⊗ which even on a Mac requires Character Viewer to add.  (Though one could argue that readability >> speed of typing in programming, and D⊗I looks better to me than kron(D,I)…)

**Comment by MikaelSlevinsky** [comment]
Whatever the outcome, I would like to have a symbol for definite integral functional.

In LightTable, I can use the LaTeX completions: \Sigma, \otimes...

**Comment by dlfivefifty** [comment]
That’s nice!  Should I switch to LightTable?

**Comment by MikaelSlevinsky** [comment]
The features I like are:
- command completion
- every word appears with a unique pastel colour, probably determined by a hash of its characters
- you can search through entire workspaces (a workspace could include multiple .jl packages)
- it is an IDE so you can run Julia in it (though I more often use terminal)

I'm sure there's way more I haven't learned yet.

I don't like that it is quite power-hungry so I only have it on my new laptop.

**Comment by MikaelSlevinsky** [comment]
It turns out \sum and \Sigma are different, lol
sum ∑, Sigma Σ

**Comment by MikaelSlevinsky** [comment]
Just going through https://github.com/JuliaLang/julia/blob/master/base/latex_symbols.jl

These are probably all the integral symbols:
\int
\iint
\iiint
\iiiint
\oint
\oiint
\oiiint
\clwintegral
\intbar
\intBar
\intx
\clockoint
\sqrint
\upint
\loint
\intcap
\intcup
\varointclockwise
\ointctrclockwise

**Comment by MikaelSlevinsky** [comment]
One problem with actually calling the functional Σ is that the user will have to write:
```julia
S = Σ(...)
S[f]
```
instead of:
```julia
Σ = Sigma(...)
Σ[f]
```

I guess I kind of had it backwards.

**Comment by MikaelSlevinsky** [comment]
`PrincipalValue` now works! If the `ProductFun` in its index has a `CauchyWeight`, it calls `Hilbert`, if not, it calls `DefiniteIntegral`. Now, to build `GreensFun` so that the SIE's linear operator can ultimately be `L = ⨍[G]`.

**Comment by MikaelSlevinsky** [comment]
Now, in the scattering example, we can have `L,f = ⨍[K0 + Kr] + im*⨍[Kim],uiΓ` instead of `L,f = ⨍[K0] + ⨍[Kr] + im*⨍[Kim],uiΓ`.

Including the imaginary part has to do with the bug I told you about last week... something to do with a couple `convert()` routines.

**Comment by dlfivefifty** [comment]
OK does the assignment mean you want me to fix the convert bugs?

**Comment by MikaelSlevinsky** [comment]
Please! :)

**Comment by dlfivefifty** [comment]
what's the precise command that breaks?

**Comment by MikaelSlevinsky** [comment]
I think the fix can be reduced to fixing this:
```julia
using ApproxFun
K = ProductFun((x,y)->cos(x)*exp(im*y)/sqrt(1-y^2),Chebyshev()⊗JacobiWeight(-.5,-.5,Chebyshev()),15,15);
S = DefiniteIntegral(Interval(-1.,1.)) # On feat-rename-Sigma branch. Otherwise S = Σ(Interval(-1.,1.))
S[K]
I+S[K]
```
The last line gives:
```
ERROR: `TimesOperator{T<:Number}` has no method matching TimesOperator{T<:Number}(::Array{BandedOperator{T},1})
 in rangespace at /Users/Mikael/.julia/v0.3/ApproxFun/src/Operators/Multiplication.jl:58
 in rangespace at /Users/Mikael/.julia/v0.3/ApproxFun/src/Operators/algebra.jl:273
 in findmaxrangespace at /Users/Mikael/.julia/v0.3/ApproxFun/src/Operators/spacepromotion.jl:61
 in promoterangespace at /Users/Mikael/.julia/v0.3/ApproxFun/src/Operators/spacepromotion.jl:93
 in promoteplus at /Users/Mikael/.julia/v0.3/ApproxFun/src/Operators/algebra.jl:35
 in + at /Users/Mikael/.julia/v0.3/ApproxFun/src/Operators/algebra.jl:122
```

**Comment by dlfivefifty** [comment]
OK Yeah probably some missing promote_type routine causing an [] to resolve to BandedOperator[] instead of BandedOperator{Complex{Float64}}[].  Should be an easy fix.

**Comment by dlfivefifty** [comment]
OK the bug is actually that Multiplication(::Ultraspherical{0},::ConstantSpace) is not defined yet.  This should be an easy fix.

	Though I found another bug in the process that promotespaces was not typing operators….  fixing this is causing other issues

**Comment by dlfivefifty** [comment]
Actually turns out that wasn’t the bug at all.  Should be fixed now (the type promotion for operators has been improved).

**Comment by MikaelSlevinsky** [comment]
Thanks again! Another LightTable shortcut is multiline tabbing.
