### ISSUE TITLE
Rethink getindex(::Operator,::ProductFun)

### ISSUE THREAD

**Issue by MikaelSlevinsky** [ApproxFun/SIE.jl#19]
Right now, it goes row by row with the operator in between multiplication by Funs.

Maybe this can be simplified by adding all the coefficients as a BandedMatrix.

**Comment by dlfivefifty** [comment]
I think this is a really good idea for 

	getindex(::Functional,::ProductFun)

which is a compact operator: i.e., can be represented as a finite-dimensional matrix.  Don’t quite see yet how this will work for

	getindex(::BandedOperator,::ProductFun)
