### ISSUE TITLE
Unified treatment of Hilbert and Cauchy Operators

### ISSUE THREAD

**Issue by MikaelSlevinsky** [ApproxFun/SIE.jl#2]
Currently, we have `Hilbert` inheriting its core structure & function from the `calculus_operator` macro (which is awesome by the way). So I was thinking could the same be done for `Cauchy` operators?

One way to do it would be to create two new operators `CauchyPlus` and `CauchyMinus`, and their abstract supertypes and wrappers. Another way would be to modify the macro and have the `immutable` types declared before. This would allow a single `Cauchy` operator to look like:

```julia
immutable Cauchy{S<:FunctionSpace,T<:Number} <: AbstractCauchy{T}
    space::S
    order::Int
    orientation::Vector{Bool}
end
```

The `calculus_operator` macro would set most things as usual. Then, one simple outer function, say `orientation(s::Union(Int,Bool),C::Cauchy)` assigns a value to a Cauchy instance's `orientation[1]`. Note that storing orientation as a `Vector{Bool}` allows its entries to be changed even though the operator is immutable.

**Comment by dlfivefifty** [comment]
There are multiple ways of defining cauchy/hilbert for a given space:

   cauchy(±1,f,z)    # pointwise definition
   hilbert(f,z)                     # pointwise definition
   hilbert(f)                        # function definition
   Cauchy(±1,f)      # operator definition, but only nice spaces in periodic case
   Hilbert(f)                        # operator definition

where ±1 stand for true/false.  We need to decide what the fall backs are when one is not defined, here are the possibilities:


   cauchy(±1,f,z) = ±0.5f[z] - im*hilbert(f,z)
   hilbert(f,z) = im*(cauchy(+1,f,z) + cauchy(-1,f,z))      # if we implement both fallbacks, we get race condition, so maybe just first fallback and make "hilbert" the thing to implement
   hilbert(f,z) = hilbert(f)[z]
   hilbert(f) = Hilbert()*f
   cauchy(±1,f,z) = (Cauchy(±1)*f)[z]    # probably not useful for intervals, so may skip this
   Cauchy(±1) = ±0.5I - im*Hilbert()    # This one is implemented

**Comment by dlfivefifty** [comment]
I'm going to implement these fall backs for now and see if we are happy:

cauchy(±1,f,z) = ±0.5f[z] - imhilbert(f,z)
hilbert(f,z) = hilbert(f)[z]
hilbert(f) = Hilbert()f
Cauchy(±1) = ±0.5I - im*Hilbert()

**Comment by MikaelSlevinsky** [comment]
That works for me. Probably should have most fallbacks in one direction unless there's ambiguity.

**Comment by MikaelSlevinsky** [comment]
I think this is as unified as it can be.
