### ISSUE TITLE
Why is the Neumann scattering density not symmetric for symmetric boundary data?

### ISSUE THREAD

**Issue by MikaelSlevinsky** [ApproxFun/SIE.jl#20]
Trying to get Neumann boundary conditions to work with the Helmholtz equation has been tricky, but this is something I didn't expect.

If an incident wave is normal to the scatterer (d=(0,-1)) then for different wave numbers (specifically k = 2, 10, 12, 20) the density may not be even. Why? The GreensFun seems to be symmetric to 14 or so digits, and the input data is obviously symmetric in this case.

**Comment by MikaelSlevinsky** [comment]
Actually, it is more appropriate for the density to be in `JacobiWeight(0.5,0.5,Ultraspherical{1}(dom))` rather than `JacobiWeight(-0.5,-0.5,Chebyshev(dom))`. In the Neumann case, the density is the jump in solution, which is therefore expected to decay to zero at the endpoints, rather than blow up at the endpoints. With today's changes @45aa1f764e9d5d30bab5ed28dd2993a989c7c0d6, the condition numbers are down from 1e16 to 1e1 (as in the Dirichlet case) and the solution is even for even input data.

**Comment by dlfivefifty** [comment]
Cool!!!

I was wondering if implementing the Chebyshev U weight was pointless because any function can also be written in the form of Chebyshev T weight where the function vanishes at the edges.  Glad to know that effort was useful!

**Comment by MikaelSlevinsky** [comment]
Ya! The missing piece for this formulation was the log singularity, and for the formulation in `JacobiWeight(+.5,+.5,Chebyshev())`, `DefiniteLineIntegral` functional is missing, though that should be easy to implement. It will be interesting to see which formulation is faster - probably the one with the fewest conversions, and a lot of those can be removed by `GreensFun` construction in the right `TensorSpace`.

It's also a big plus because the Neumann boundary condition (sound-hard) is more prevalent in nature.
