### ISSUE TITLE
Speed up LowRankFun constructor

### ISSUE THREAD

**Issue by MikaelSlevinsky** [ApproxFun/SIE.jl#5]
I'm happy to do this one, but would like to put some ideas on the table first. The solver is fast enough now that you cannot see a lag in @manipulate, but for SIEs with non-trivial kernels, creating the LowRankFuns is now a bottleneck.

- Probably the easiest thing that will help is to have a constructor for Funs that recycles the function samples. I think this would have an asymptotic savings of 1/2 and therefore 1/4 for LowRankFuns?
- Write some parallel code using the CUDA or OpenCL Julia packages to evaluate the function at all the points in parallel.

**Comment by dlfivefifty** [comment]
@ajt60gaibb implemented some improvements to the 1D constructor to avoid over-resolving functions in the branch

https://github.com/ApproxFun/ApproxFun.jl/tree/fix-ApproxFun-scalarconstructor  

but this never got merged because it broke some JacobiWeight tests.  Probably not the problem here, but maybe its worthwhile finishing this merge?

**Comment by dlfivefifty** [comment]
Also, have you compared the timings between LowRankFun and chebfun2?  I'm not sure LowRankFun is actually faster, if it's not then there's probably some more basic improvements needed.  (I put almost zero thought into LowRankFun, it was just hacked together and I'm always surprised when it works.)  I don't have a working Matlab so can't check.

**Comment by dlfivefifty** [comment]
And for SIE kernels there might be an inherent diagonal dominance that can avoid the "findmax" step.  Assuming the diagonal dominance is not just an artifact of the singular kernel (which is factored out)

**Comment by MikaelSlevinsky** [comment]
Is there a convolution-type formula to represent T_n(y-x) as a sum of products of Chebyshev polynomials in both variables individually? Then, a 1D constructor could be used for diagonal SIE kernels K(y-x) and transformed into a LowRankFun or TensorFun.

**Comment by ajt60gaibb** [comment]
There is for Laguerre and Hermite polynomials, see http://dlmf.nist.gov/18.18#E38 and http://dlmf.nist.gov/18.18#E39.  But for `Tn(y-x)` I do not know exactly what you want since the arguments to Chebyshev polynomials are usually on `[-1,1]`.  What intervals do `y` and `x` live on?

**Comment by ajt60gaibb** [comment]
The closest thing I can think of looks like this: http://dlmf.nist.gov/18.18#E8

**Comment by dlfivefifty** [comment]
We could just precompute the expansion for each T_k, though maybe that's not so elegant or fast

**Comment by dlfivefifty** [comment]
Can't you just build it up from three term recurrence?

**Comment by MikaelSlevinsky** [comment]
Good point @ajt60gaibb and sorry for the confusion. Since both `y` and `x` are in `[-1,1]`, a kernel that is a function of the difference would be on `[-2,2]` and therefore would be expanded in `T_n((y-x)/2)`.

**Comment by MikaelSlevinsky** [comment]
*Also, have you compared the timings between LowRankFun and chebfun2? I'm not sure LowRankFun is actually faster, if it's not then there's probably some more basic improvements needed. (I put almost zero thought into LowRankFun, it was just hacked together and I'm always surprised when it works.) I don't have a working Matlab so can't check.*

I found that the `chebfun2` is much more accurate for functions of higher rank, but slower.

Anyways, my uses for this issue are mostly mitigated by the new `ProductFun` constructor. Perhaps we can aim for nested Chebyshev points and recycled function samples to get the simple savings.

**Comment by MikaelSlevinsky** [comment]
I didn't really consider this before because I was convinced the fastest way would be to use an addition theorem in coefficient space, but perhaps the implied symmetry between source and field points of a Green's function can reduce the search space for approximate maxima in the low rank construction and preserves the symmetry through complete pivoting. Will look into this shortly.

**Comment by ajt60gaibb** [comment]
Usually, complete pivoting only preserves symmetry if the underlying Green's function is positive definite so the pivots are always on the diagonal.  If this isn't the case, then one can sometimes preserve symmetry by using 2x2 matrices as pivots (but still not sure how to reduce the search space).

**Comment by MikaelSlevinsky** [comment]
Thanks Alex!

**Comment by MikaelSlevinsky** [comment]
- For Hermitian positive-definite "cmatrices," the `LowRankPositiveDefiniteFun` constructor introduces a significant speed-up:

```julia
julia> using ApproxFun, SIE

julia> sp1,sp2 = Chebyshev(),Chebyshev()
(Chebyshev(【-1.0,1.0】),Chebyshev(【-1.0,1.0】))

julia> f(x,y) = besselj0(30abs(y-x))
f (generic function with 1 method)

julia> @time F = LowRankFun(f,sp1,sp2);
elapsed time: 0.565386061 seconds (119788788 bytes allocated, 19.01% gc time)

julia> @time G = LowRankPositiveDefiniteFun(f,sp1,sp2);
elapsed time: 0.044882095 seconds (11273888 bytes allocated)

julia> @time H = ProductFun(f,sp1,sp2;method=:convolution);
elapsed time: 0.020821332 seconds (8847984 bytes allocated)
```

- For convolution-type kernels, the `ConvolutionProductFun` also introduces a significant speed-up:

```julia
julia> using ApproxFun, SIE

julia> sp1,sp2 = Chebyshev([-1.0-0.5im,1.0+0.5im]),Laurent(Circle(-0.5+0.5im,0.5))
(Chebyshev(【-1.0 - 0.5im,1.0 + 0.5im】),Laurent(Circle{Complex{Float64},Float64}(-0.5 + 0.5im,0.5)))

julia> f(x,y) = besselj0(30abs(y-x))
f (generic function with 1 method)

julia> @time F = LowRankFun(f,sp1,sp2);
elapsed time: 17.878112127 seconds (11624238844 bytes allocated, 57.94% gc time)

julia> @time H = ProductFun(f,sp1,sp2;method=:convolution);
elapsed time: 0.034836927 seconds (15682372 bytes allocated)
```

**Comment by ajt60gaibb** [comment]
Cool.
