### ISSUE TITLE
Cauchy bug?

### ISSUE THREAD

**Issue by MikaelSlevinsky** [ApproxFun/SIE.jl#8]
Are these lines typos?

https://github.com/ApproxFun/SIE.jl/blob/master/src/Cauchy.jl#L81
https://github.com/ApproxFun/SIE.jl/blob/master/src/Cauchy.jl#L156
https://github.com/ApproxFun/SIE.jl/blob/master/src/singfuncauchy.jl#L202

Seems like they should be like 

https://github.com/ApproxFun/SIE.jl/blob/master/src/Cauchy.jl#L114

or the `newret` serves no purpose.

**Comment by dlfivefifty** [comment]
Yep!

	I’m confused why I didn’t just use resize! though.

**Comment by MikaelSlevinsky** [comment]
Solved by @feb93218878c01086fc4986d69875c8c72b35056.
