### ISSUE TITLE
Cauchy/Stieltjes(JacobiWeight{Chebyshev},...)

### ISSUE THREAD

**Issue by MikaelSlevinsky** [ApproxFun/SIE.jl#9]
To me, this seems problematic because unravelling the `dirichlettransform` is Toeplitz and this will make it hard to write these as banded operators in the original basis (`JacobiWeight{Chebyshev}`).

Does it make sense to add `Hilbert`, `Cauchy` and `Stieltjes` in `JacobiWeight{ChebyshevDirichlet}` space for inverse square root singularities?

**Comment by MikaelSlevinsky** [comment]
I guess `Hilbert(JacobiWeight(-.5,-.5,ApproxFun.ChebyshevDirichlet()),1)` can already be declared! That's really cool - probably uses the Conversion operator from ChebyshevD to Chebyshev, right?

This means that so long as we have Cauchy/Stieltjes with domain spaces ChebyshevD - or any one which will be banded and have a banded conversion to the rangespace of Hilbert -, then it will be a go!

**Comment by MikaelSlevinsky** [comment]
Also, what do you think of:

S f(z) := 1/π \int_Γ f(t)/(t-z) dt

as a definition for Stieltjes? This way, Hilbert on a PiecewiseSpace would simply be H on diagonals and S off. Currently, it looks like everything's multiplied by π anyway.

**Comment by dlfivefifty** [comment]
My only issue is that Stieljes feels like the wrong name.. But Cauchy and Stieljes are used all over the place with different normalisations so maybe its not so bad

**Comment by dlfivefifty** [comment]
We could match my paper

	http://www.maths.usyd.edu.au/u/olver/papers/SingularIntegrals.pdf

And call both versions "Hilbert", where the current hilbert is the special case where the domains match.  Fortunately for us, it will be Hilbert{S,Chebyshev} when they are different and Hilbert{S,V} with V≠Chebyshev when they are the same domain.

	There may eventually be Hilbert{Legendre,Legendre} for domains not equal, but again, it won't be Hilbert{Legendre,Legendre} when they are the same.  

	This way Stieljes will match wikipedia.  and then we just define

	Stieljes(d,r)=-π*Hilbert(d,r)
	Cauchy(d,r)=-im*Hilbert(d,r)

in case people want the other normalizations.

**Comment by MikaelSlevinsky** [comment]
That's probably the best idea.

**Comment by MikaelSlevinsky** [comment]
It turns out the following code works, but why isn't a `Fun` in `ChebyshevDirichlet{1,1}()` space not the same as taking the `dirichlettransform` of the coefficients? I believe only the first coefficient is different. This had me confused for a while.

```
using ApproxFun, SIE
ds1 = JacobiWeight(-.5,-.5,ApproxFun.ChebyshevDirichlet{1,1}())
ds2 = JacobiWeight(-.5,-.5,Chebyshev())
rs = Chebyshev([2.,4.])
f2 = Fun(x->exp(x)/sqrt(1-x^2),ds2)
f1 = Fun(ApproxFun.dirichlettransform(f2.coefficients),ds1) #f1 = Fun(x->exp(x)/sqrt(1-x^2),ds1)
C = Cauchy(ds1,rs)

(C*f1)[3.]
cauchy(f2,3.)
```

**Comment by MikaelSlevinsky** [comment]
Although, a disadvantage of calling both versions Hilbert is that the current Hilbert would not have such simple addentries! as it currently does.

**Comment by dlfivefifty** [comment]
How do you feel about moving order to be a type parameter?  This would be changed for all calculus operators I suppose, so

	Derivative{Chebyshev,T}  -> 	Derivative{1,Chebyshev,T}

It would allow removing the “if order ==“ lines from all the addentries!.  Having all the cases in the same addentries! bothers me a little…since it makes the implementation much longer.  


	The one draw back is the parameter must be an int or bool, not a float, so it would break future support for fractional derivativatives/hilbert.  Though maybe these are different enough to warrant a different name for the operator…


	Perhaps not worth doing right now though.

**Comment by dlfivefifty** [comment]
I’m definitely in favour of changing to 1/π normalizing and calling it something other than Stieltjes, mainly because I constantly misspell Stieltjes :)

**Comment by MikaelSlevinsky** [comment]
OffHilbert has the normalization by π and also has the analogous logkernel operator for order 0.

Currently trying to get this to work for Laplace's equation with fixed potential on Intervals (similar to scattering except different Green's function and "incident" piece). The following syntax in principle now works:

```julia
using ApproxFun, SIE
dom = Interval([-2.5,-0.5])∪Interval([0.5,2.5])
sp = ApproxFun.PiecewiseSpace(map(ApproxFun.ChebyshevDirichlet{1,1},dom.domains))
wsp = ApproxFun.PiecewiseSpace([JacobiWeight(-.5,-.5,sp.spaces[i]) for i=1:length(sp)])
H0 = Hilbert(wsp,0)
```

I don't expect the name to stick - I'm just messily trying to move things along

Next step is to try to build in non-constant kernels somewhere as getindex of HilbertWrapper?/InterlaceOperator?

**Comment by MikaelSlevinsky** [comment]
I think there's something off about the normalization of `logkernel`/`stieltjesintegral`/`cauchyintegral` for non-canonical domains:

```julia
w = Fun(x->1/sqrt((x+3.5)*(-.5-x)),JacobiWeight(-.5,-.5,Chebyshev([-3.5,-0.5])))
quadgk(x->w[x]*log(abs(x-7.))/π,-3.5,-0.5)
logkernel(w,7)/π
```

Hilbert(space(w),0) seems to be working fine:

```julia
Hilbert(space(w),0)*w
quadgk(x->w[x]*log(abs(x+2.))/π,-3.5,-2.,-0.5)
quadgk(x->w[x]*log(abs(x+1.5))/π,-3.5,-1.5,-0.5)
```

**Comment by dlfivefifty** [comment]
I think this is all set!
